"""Legacy source-bot import package.

The stable CLI entry point is the thin shim ``backend/scripts/import_legacy.py``
(documented in docs/migrations and downloaded verbatim by scripts/install.sh);
it re-exports this package's public surface.
"""

from __future__ import annotations

from .cli import (
    build_arg_parser,
    main,
    parse_only,
    parse_tariff_map,
    run_import,
)
from .common import (
    GIB,
    PAYMENT_WEBHOOK_PATHS,
    SOURCE,
    SUPPORTED_REMNASHOP_PROVIDER_TYPES,
    UNSUPPORTED_REMNASHOP_PROVIDER_TYPES,
    normalize_async_postgres_dsn,
)
from .remnashop import (
    RemnashopImporter,
)
from .remnashop_data import (
    _add_tariff_map_entries,
    _duration_prices_by_id,
    _durations_by_plan,
    _extract_panel_subscription_uuid,
    _legacy_user_metadata,
    _provider_value,
    _remnashop_currency_key,
    _remnashop_enum_text,
    _remnashop_plan_enabled,
    _remnashop_plan_tariff_base_key,
    _remnashop_price_value,
    _remnashop_squad_uuids,
    _remnashop_tariff_slug,
    _unique_tariff_key,
    remnashop_build_tariff_catalog,
    remnashop_days_to_months,
    remnashop_months_from_plan_snapshot,
    remnashop_notification_overrides,
    remnashop_plan_type,
    remnashop_pricing_amount,
    remnashop_pricing_currency,
    remnashop_purchased_gb,
    remnashop_purchased_hwid_devices,
    remnashop_row_telegram_id,
    remnashop_sale_mode,
    remnashop_subscription_provider,
    remnashop_tariff_key,
    remnashop_traffic_gb_to_bytes,
    remnashop_transaction_status,
)
from .remnashop_env import (
    _add_override,
    _clean_url,
    _is_encrypted_remnashop_value,
    _is_placeholder_setting_value,
    _normalize_currency,
    _normalize_gateway_type,
    _provider_mapping_result,
    _remnashop_panel_api_url,
    _source_public_base_from_env,
    _support_link_from_username,
    _target_webhook_url,
    parse_remnashop_env_text,
    read_remnashop_env_file,
    remnashop_decrypt_recursive,
    remnashop_decrypt_value,
    remnashop_env_overrides,
    remnashop_payment_gateway_overrides,
    remnashop_post_migration_actions,
    remnashop_source_urls_from_env,
)

__all__ = [
    "GIB",
    "PAYMENT_WEBHOOK_PATHS",
    "SOURCE",
    "SUPPORTED_REMNASHOP_PROVIDER_TYPES",
    "UNSUPPORTED_REMNASHOP_PROVIDER_TYPES",
    "RemnashopImporter",
    "_add_override",
    "_add_tariff_map_entries",
    "_clean_url",
    "_duration_prices_by_id",
    "_durations_by_plan",
    "_extract_panel_subscription_uuid",
    "_is_encrypted_remnashop_value",
    "_is_placeholder_setting_value",
    "_legacy_user_metadata",
    "_normalize_currency",
    "_normalize_gateway_type",
    "_provider_mapping_result",
    "_provider_value",
    "_remnashop_currency_key",
    "_remnashop_enum_text",
    "_remnashop_panel_api_url",
    "_remnashop_plan_enabled",
    "_remnashop_plan_tariff_base_key",
    "_remnashop_price_value",
    "_remnashop_squad_uuids",
    "_remnashop_tariff_slug",
    "_source_public_base_from_env",
    "_support_link_from_username",
    "_target_webhook_url",
    "_unique_tariff_key",
    "build_arg_parser",
    "main",
    "normalize_async_postgres_dsn",
    "parse_only",
    "parse_remnashop_env_text",
    "parse_tariff_map",
    "read_remnashop_env_file",
    "remnashop_build_tariff_catalog",
    "remnashop_days_to_months",
    "remnashop_decrypt_recursive",
    "remnashop_decrypt_value",
    "remnashop_env_overrides",
    "remnashop_months_from_plan_snapshot",
    "remnashop_notification_overrides",
    "remnashop_payment_gateway_overrides",
    "remnashop_plan_type",
    "remnashop_post_migration_actions",
    "remnashop_pricing_amount",
    "remnashop_pricing_currency",
    "remnashop_purchased_gb",
    "remnashop_purchased_hwid_devices",
    "remnashop_row_telegram_id",
    "remnashop_sale_mode",
    "remnashop_source_urls_from_env",
    "remnashop_subscription_provider",
    "remnashop_tariff_key",
    "remnashop_traffic_gb_to_bytes",
    "remnashop_transaction_status",
    "run_import",
]
