export type DemoProviderCurrencySupport = {
  id: string;
  provider_key: string;
  provider_label: string;
  settings_path: string[];
  label: string;
  enabled: boolean;
  configured: boolean;
  admin_only: boolean;
  price_source: string;
  currencies: string[];
  accepts_any_currency: boolean;
  supports_default_currency: boolean;
  directly_supports_default_currency: boolean;
  default_currency: string;
};

export function demoProviderCurrencySupport(): DemoProviderCurrencySupport[] {
  return [
    {
      id: "freekassa",
      provider_key: "freekassa",
      provider_label: "FreeKassa",
      settings_path: ["payments", "freekassa"],
      label: "FreeKassa / SBP",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "platega_sbp",
      provider_key: "platega",
      provider_label: "Platega SBP/card",
      settings_path: ["payments", "platega", "sbp"],
      label: "Pay with card (SBP)",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "platega_crypto",
      provider_key: "platega",
      provider_label: "Platega Crypto",
      settings_path: ["payments", "platega", "crypto"],
      label: "Crypto",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["USDT", "TON"],
      accepts_any_currency: false,
      supports_default_currency: false,
      directly_supports_default_currency: false,
      default_currency: "rub",
    },
    {
      id: "severpay",
      provider_key: "severpay",
      provider_label: "SeverPay",
      settings_path: ["payments", "severpay"],
      label: "SeverPay",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "wata",
      provider_key: "wata",
      provider_label: "Wata",
      settings_path: ["payments", "wata"],
      label: "Wata",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "yookassa",
      provider_key: "yookassa",
      provider_label: "YooKassa",
      settings_path: ["payments", "yookassa"],
      label: "YooKassa",
      enabled: false,
      configured: false,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "stars",
      provider_key: "telegram_stars",
      provider_label: "Telegram Stars",
      settings_path: ["payments", "telegram-stars"],
      label: "Telegram Stars",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "stars",
      currencies: ["XTR"],
      accepts_any_currency: false,
      supports_default_currency: false,
      directly_supports_default_currency: false,
      default_currency: "rub",
    },
    {
      id: "cryptopay",
      provider_key: "cryptopay",
      provider_label: "CryptoPay",
      settings_path: ["payments", "cryptopay"],
      label: "CryptoPay",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["USDT", "TON", "BTC"],
      accepts_any_currency: false,
      supports_default_currency: false,
      directly_supports_default_currency: false,
      default_currency: "rub",
    },
    {
      id: "heleket",
      provider_key: "heleket",
      provider_label: "Heleket",
      settings_path: ["payments", "heleket"],
      label: "Heleket",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB", "USDT"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "paykilla",
      provider_key: "paykilla",
      provider_label: "PayKilla",
      settings_path: ["payments", "paykilla"],
      label: "PayKilla",
      enabled: true,
      configured: false,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "lava",
      provider_key: "lava",
      provider_label: "LAVA",
      settings_path: ["payments", "lava"],
      label: "LAVA",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "cloudpayments",
      provider_key: "cloudpayments",
      provider_label: "CloudPayments",
      settings_path: ["payments", "cloudpayments"],
      label: "CloudPayments",
      enabled: true,
      configured: true,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB", "USD", "EUR", "GBP", "KZT", "UAH", "BYN", "AZN", "AMD", "KGS"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
    {
      id: "stripe",
      provider_key: "stripe",
      provider_label: "Stripe",
      settings_path: ["payments", "stripe"],
      label: "Stripe",
      enabled: false,
      configured: false,
      admin_only: false,
      price_source: "rub",
      currencies: ["RUB", "USD", "EUR", "GBP"],
      accepts_any_currency: false,
      supports_default_currency: true,
      directly_supports_default_currency: true,
      default_currency: "rub",
    },
  ];
}
